---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-myapp
  namespace: default
spec:
  storageClassName: test-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
